### PR TITLE
Added Guide Making an old GDPS version.

### PR DESCRIPTION
**Pull request by Redactedslair**
Everything should be good. Let me know if there are issues.

### CODE REVIEW

**Comment by Redactedslair** [comment]
29 days of forgor

**Comment by Redactedslair** [comment]
Damn 3 months that is crazy

**Comment by Jecket22** [comment]
Could (...and should) be improved, mostly language wise, but works for now. Sorry for the delay

**Comment by Jecket22** [comment]
I wanted to pull not close

**Pull request merged**
