### PR TITLE
Added a tutorial on creating daily levels.

### PR DESCRIPTION
**Pull request by xavwashere**
^^

### CODE REVIEW

**Comment by Drtrayblox7855** [comment]
This is the hard way to add daily levels. You can just type the command '!daily' on a level and it will be the daily level.

**Comment by MigMatos** [comment]
> This is the hard way to add daily levels. You can just type the command '!daily' on a level and it will be the daily level.

but... it is never bad to explain alternatives

**Comment by Jecket22** [comment]
That is indeed a *overcomplicated* method of creating daily levels. However I like how you make the guide overall. I won't merge this since it's a lot more complicated than just running the `!daily` command, but I think if you would make a page like this for other things like Quests for example (or anything really that can't be done in-game / through the tools page), then your pages could come in handy.

**Comment by xavwashere** [comment]
Thanks for reading, I'll try make a guide for quests. I honestly didn't know you could do !daily lol.

**Comment by xavwashere** [comment]
Oh by the way, with !daily you can't set dailies in advance. But with this guide, you can.

**Comment by Jecket22** [comment]
> Oh by the way, with !daily you can't set dailies in advance. But with this guide, you can.

No you can, they'll get queued on top

**Comment by xavwashere** [comment]
I stand corrected again. :)

**Pull request closed without merging**
