### PR TITLE
Create Detailed explanation of phpmyadmin tables and columns.md

### PR DESCRIPTION
**Pull request by nojnis**
this took SO long to make. I will fix anything that is needed to be fixed or that u prefer me to change

### CODE REVIEW

**Comment by Redactedslair** [comment]
Jesus christ 700 lines

**Review by Redactedslair — APPROVED** [review]
looks good 👍👍👍👍👍👍

**Comment by nojnis** [comment]
now it is 100% finished for now

**Comment by nojnis** [comment]
ok ignore rthis i submitted one with lots of changes

**Pull request closed without merging**
